output_dir: "runs/stats/stats-olmo-7b-ins-ft-1k/flan-v2/ft/{ocl_task_category}/task_{ocl_task_id}"

templates:
  ocl_task_id: -1
  ocl_task_category: "debug"


stat:
  ocl_task_category: "{ocl_task_category}"
  ocl_task_id: "{ocl_task_id}"
  pt_task_id: -1
  pt_task_category: "tulu"
  task_model_dir: "runs/olmo-7b-ft-ins/{ocl_task_category}-1k-full-ft-lr2e-6/task_{ocl_task_id}/model_save/"
  partition: 'train'
exp_group: "tulu"

model_name: "allenai/OLMo-7B-Instruct-hf"
tokenizer_name: "allenai/OLMo-7B-Instruct-hf"
chat_template_name: "allenai/OLMo-7B-Instruct-hf"

tulu:
  path: "data/tulu_sample/sample_10k_flan.json"