exp_group: "dolma"

dolma_base_dir: "data/dolma_v1_6-sample_tok_mm"
paloma_base_dir: "data/paloma_tok"

dolma_split_start: 0
dolma_split_stop: 1

is_seq2seq: false
model_name: "allenai/OLMo-7B-hf"

output_dir: "runs_olmo_ft/debug"
max_input_length: 1024

save_steps: -1

learning_rate: 5.0e-6
gradient_accumulation_steps: 1

is_lm_sft: true

per_device_eval_batch_size: 2
per_device_train_batch_size: 2

ocl_steps: 5000
bf16: true
fp16: false
n_gpu: 4 

is_continual: false

optimizer: 'paged_adamw_8bit'
deepspeed: null

shuffle_ocl: false
shuffle_ocl_seed: 0

templates:
  dummy: 1

peft: null


replay:
  enabled: false
  task_category: 'dolma_sample'
  heldout_num: 10000
  mixture_method: 'random'
  mixture_ratio: 0.125
  seed: 0
  truncate_pt_ds: -1

stream:
  bs: 4
  n_step_per_batch: 1


ocl_val_step: 50
ocl_val_max_batch: -1
ans_start_pattern: "<|assistant|>"

dolma:
  sample_path: "data/dolma_chunked_sample/stratified_1_100_tokenize_fix.pkl"

olmo2pt:
  sample_path: "data/olmo2_mix/olmo-mix-1124/olmo2_truncated_examples_sample_filterlen.pkl"

pile:
  sample_path: "data/pile_sample/pile_first_10k.pkl"

mmlu_tasks:
  - abstract_algebra
  - anatomy
  - astronomy
  - business_ethics
  - clinical_knowledge
  - college_biology
  - college_chemistry
  - college_computer_science
  - college_mathematics
  - college_medicine
  - college_physics
  - computer_security
  - conceptual_physics
  - econometrics
  - electrical_engineering
  - elementary_mathematics
  - formal_logic
  - global_facts
  - high_school_biology
  - high_school_chemistry
  - high_school_computer_science
  - high_school_european_history
  - high_school_geography
  - high_school_government_and_politics
  - high_school_macroeconomics
  - high_school_mathematics
  - high_school_microeconomics
  - high_school_physics
  - high_school_psychology
  - high_school_statistics
  - high_school_us_history
  - high_school_world_history
  - human_aging
  - human_sexuality
  - international_law
  - jurisprudence
  - logical_fallacies
  - machine_learning
  - management
  - marketing
  - medical_genetics
  - miscellaneous
  - moral_disputes
  - moral_scenarios
  - nutrition
  - philosophy
  - prehistory
  - professional_accounting
  - professional_law
  - professional_medicine
  - professional_psychology
  - public_relations
  - security_studies
  - sociology
  - us_foreign_policy
  - virology
  - world_religions

bbh_tasks:
  - boolean_expressions
  - causal_judgement
  - date_understanding
  - disambiguation_qa
  - dyck_languages
  - formal_fallacies
  - geometric_shapes
  - hyperbaton
  - logical_deduction_five_objects
  - logical_deduction_seven_objects
  - logical_deduction_three_objects
  - movie_recommendation
  - multistep_arithmetic_two
  - navigate
  - object_counting
  - penguins_in_a_table
  - reasoning_about_colored_objects
  - ruin_names
  - salient_translation_error_detection
  - snarks
  - sports_understanding
  - temporal_sequences
  - tracking_shuffled_objects_five_objects
  - tracking_shuffled_objects_seven_objects
  - tracking_shuffled_objects_three_objects
  - web_of_lies
  - word_sorting

flan_by_task_dir: "data/flan_by_task"
flan_tasks:
  - aeslc_10templates
  - ag_news_subset_10templates
  - anli_r1_10templates
  - anli_r2_10templates
  - anli_r3_10templates
  - arc_challenge_10templates
  - arc_easy_10templates
  - bool_q_10templates
  - cb_10templates
  - cnn_dailymail_10templates
  - cola_10templates
  - common_gen_10templates
  - copa_10templates
  - coqa_10templates
  - cosmos_qa_10templates
  - dart_10templates
  - definite_pronoun_resolution_10templates
  - drop_10templates
  - e2e_nlg_10templates
  - fix_punct_10templates
  - gigaword_10templates
  - glue_mrpc_10templates
  - glue_qqp_10templates
  - hellaswag_10templates
  - imdb_reviews_10templates
  - math_dataset_10templates
  - mnli_matched_10templates
  - mnli_mismatched_10templates
  - multi_news_10templates
  - multirc_10templates
  - natural_questions_10templates
  - openbookqa_10templates
  - opinion_abstracts_idebate_10templates
  - opinion_abstracts_rotten_tomatoes_10templates
  - para_crawl_enes_10templates
  - paws_wiki_10templates
  - piqa_10templates
  - qnli_10templates
  - quac_10templates
  - record_10templates
  - rte_10templates
  - samsum_10templates
  - sentiment140_10templates
  - snli_10templates
  - squad_v1_10templates
  - squad_v2_10templates
  - sst2_10templates
  - story_cloze_10templates
  - stsb_10templates
  - trec_10templates
  - trivia_qa_10templates
  - true_case_10templates
  - web_nlg_en_10templates
  - wic_10templates
  - wiki_lingua_english_en_10templates
  - wmt14_enfr_10templates
  - wmt16_translate_csen_10templates
  - wmt16_translate_deen_10templates
  - wmt16_translate_fien_10templates
  - wmt16_translate_roen_10templates
  - wmt16_translate_ruen_10templates
  - wmt16_translate_tren_10templates
  - wnli_10templates
  - word_segment_10templates
  - wsc_10templates
  - yelp_polarity_reviews_10templates

bbh:
  path: "data/BIG-Bench-Hard/bbh_split"
  prompt_path: "data/BIG-Bench-Hard/cot-prompts"
  is_cot: false

mmlu:
  path: "data/mmlu/data/"
  cot_prompt_path: "data/flan-2/mmlu-cot.json"
  few_shot_k: 5

  is_cot: false
  is_few_shot: true
  answer_type: "text"
  train_split: "dev"

tulu:
  path: "data/tulu_sample/sample_1k.json"

use_flash_attention_2: true

truthful_qa_tasks:
  - Nutrition
  - Stereotypes
  - Confusion
  - Psychology
  - Language
  - Sociology
  - Finance
  - Indexical Error
  - Science
  - Misconceptions
  - Economics
  - Education
  - Proverbs
  - Conspiracies
  - Religion
  - Statistics
  - Misquotations
  - Subjective
  - Law
  - History
  - Fiction
  - Mandela Effect
  - Politics
  - Misinformation
  - Logical Falsehood
  - Distraction
  - Weather
  - Myths and Fairytales
  - Superstitions
  - Advertising
  - Paranormal
  - Health

tulu_tasks:
  - open_orca
  - oasst1
  - lima
  - code_alpaca
  - gpt4_alpaca
  - cot
  - science
  - flan_v2
  - sharegpt
  - hard_coded
  - wizardlm

dolly_tasks:
  - brainstorming
  - closed_qa
  - information_extraction
  - classification
  - open_qa
  - general_qa
  - creative_writing
  - summarization

chat_template_name: "allenai/OLMo-7B-Instruct-hf"

ocl:
  task_category: "flan"
  task_id: "{TASK_ID}"


gradient_checkpointing: true

