output_dir: "runs/stats/stats-pythia/{size}/{ocl_task_category}-{ocl_step}-lr2e-6/task_{ocl_task_id}"

templates:
  ocl_task_id: -1
  ocl_task_category: "debug"
  ocl_step: "1k"
  size: "not_set"


stat:
  ocl_task_category: "{ocl_task_category}"
  ocl_task_id: "{ocl_task_id}"
  pt_task_id: -1
  pt_task_category: "pile"
  task_model_dir: "runs/pythia-ft/{size}/{ocl_task_category}-{ocl_step}-full-ft-lr2e-6/task_{ocl_task_id}/model_save/"

exp_group: "pile"

model_name: "EleutherAI/pythia-{size}"
chat_template_name: "allenai/OLMo-7B-Instruct-hf"